version: '2'
services:
    mblms-app:
        image: mblms
        external_links:
            - mblms-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/mblms
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    mblms-postgresql:
        extends:
            file: postgresql.yml
            service: mblms-postgresql
